name: Teste Simples

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  mensagem:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensagem
        run: echo "Olá, Karollyne! O workflow está funcionando 🎉"